[package]
name = "local-model"
version = "0.1.0"
edition = "2024"

[dependencies]
poha-am = { workspace = true }
poha-cactus-model = { workspace = true }
poha-file = { workspace = true }
poha-model-downloader = { workspace = true }
poha-whisper-local-model = { workspace = true }

serde = { workspace = true }
specta = { workspace = true }
